// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4S4Z2PzgtSN0feCqoXMxoSQ2ab8-MYc',
    appId: '1:960616738857:web:6d1a5497602d8345b72c38',
    messagingSenderId: '960616738857',
    projectId: 'fitnessapp-group03',
    authDomain: 'fitnessapp-group03.firebaseapp.com',
    databaseURL: 'https://fitnessapp-group03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitnessapp-group03.appspot.com',
    measurementId: 'G-CNDFQE1XKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLqAMjYEoaaugpoTQmEA4D9eBOLUN478g',
    appId: '1:960616738857:android:b26a1629a10360b1b72c38',
    messagingSenderId: '960616738857',
    projectId: 'fitnessapp-group03',
    databaseURL: 'https://fitnessapp-group03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitnessapp-group03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVImYo5bLRLeVFe3q2UWlUH0vuWlTHJE',
    appId: '1:960616738857:ios:e4fb2de9be35d24bb72c38',
    messagingSenderId: '960616738857',
    projectId: 'fitnessapp-group03',
    databaseURL: 'https://fitnessapp-group03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitnessapp-group03.appspot.com',
    iosBundleId: 'com.mattkje.WatchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzVImYo5bLRLeVFe3q2UWlUH0vuWlTHJE',
    appId: '1:960616738857:ios:8f964213c1ca4adab72c38',
    messagingSenderId: '960616738857',
    projectId: 'fitnessapp-group03',
    databaseURL: 'https://fitnessapp-group03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitnessapp-group03.appspot.com',
    iosBundleId: 'ntnu.group03.fitnessappIdata2503',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4S4Z2PzgtSN0feCqoXMxoSQ2ab8-MYc',
    appId: '1:960616738857:web:019f26707874c3eab72c38',
    messagingSenderId: '960616738857',
    projectId: 'fitnessapp-group03',
    authDomain: 'fitnessapp-group03.firebaseapp.com',
    databaseURL: 'https://fitnessapp-group03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitnessapp-group03.appspot.com',
    measurementId: 'G-TMFGHC0BMB',
  );
}
